### ISSUE TITLE
Outdated dependencies & MoneyRails configure error. 

### ISSUE THREAD

**Issue by jonathansimmons** [phlegx/money-currencylayer-bank#1]
I noticed the gemspec dependencies a a bit outdated. 

Also once I had the gem specified and initializer setup I kept getting the following error: 

``` ruby
undefined method `configure' for MoneyRails:Module (NoMethodError)
```

**Comment by phlegx** [comment]
@jonathansimmons please use this `money-rails` fork https://github.com/phlegx/money-rails. Here we have repaired the outdated dependencies.

**Comment by jonathansimmons** [comment]
Hmm having to use a custom fork of a dependency seems janky...

Why can't your gem stay in support of the shipping money-rails gem?

**Comment by phlegx** [comment]
@jonathansimmons please use **money-rails v1.6.0** and you don't need to use the fork.
