### ISSUE TITLE
Bug handling new API endpoint?

### ISSUE THREAD

**Issue by stevenou** [phlegx/money-currencylayer-bank#13]
I believe the following line should be deleted in order to correctly handle the new API endpoint. Right now, when using the new API endpoint, I believe it tries to access it without any credentials, and you end up with a 401 error. I imagine this line was meant to be replaced by the line following it. https://github.com/phlegx/money-currencylayer-bank/blob/a6ba2729e11416784e97c3522c984f3cbd772d78/lib/money/bank/currencylayer_bank.rb#L261

**Comment by phlegx** [comment]
@stevenou omg! Your right. Thx for reporting.
