### ISSUE TITLE
unrecognized option: apikey (ArgumentError)

### ISSUE THREAD

**Issue by stevenou** [phlegx/money-currencylayer-bank#14]
Thank you for fixing the issue with `open_url` so quickly. I just tried the new version but actually I think there's another bug:

```
irb(main):003:0> Money.default_bank.send(:exchange_rates)
/Users/stevenou/.rbenv/versions/3.1.2/lib/ruby/3.1.0/open-uri.rb:111:in `block in check_options': unrecognized option: apikey (ArgumentError)
/Users/stevenou/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/json-2.6.2/lib/json/common.rb:216:in `parse': 859: unexpected token at '' (JSON::ParserError)
```

I _think_ this might be specific to ruby 3 and has something to do with keyword args vs hashes, but I'm not sure about the specifics. I was able to get it to work on my end by changing it to `'apikey' => access_key`
https://github.com/phlegx/money-currencylayer-bank/blob/b409f8721e8cf87e7a33da97ffa622d6261f2a0c/lib/money/bank/currencylayer_bank.rb#L261

**Comment by phlegx** [comment]
@stevenou can you please try out tag v0.7.2?

**Comment by stevenou** [comment]
seems to all be working correctly for me 👍
