### ISSUE TITLE
Bug on service not available

### ISSUE THREAD

**Issue by imlex7** [phlegx/money-currencylayer-bank#5]
bank/currency_layer/layer_ban.rb  (185)
# Update all rates from CurrencylayerBank JSON
 # @return [Array] array of exchange rates  
   def update_rates(straight = false)
        store.reset!
        rates = exchange_rates(straight).each do |exchange_rate| <<< exception **undefined method each for nil** on service at _apilayer.net/api/live_ not availble

Please fix

**Comment by joerghaubrichs** [comment]
Hi, I've seen that error more recently, has it been fixed?

**Comment by vickodin** [comment]
The same error happened

**Comment by phlegx** [comment]
Please try out version 0.5.7 and give more information about Ruby version and the complete error log.

**Comment by hrdwdmrbl** [comment]
I still get this, even on the latest 0.5.7

For some reason, calling `update_rates` seems to have fixed the problem...
